### ISSUE TITLE
Support include and exclude patterns for path ruleset

### ISSUE THREAD

**Issue by JordanSussman** [go-vela/types#65]
## Description

Update the `ruleset` to allow include and exclude logic for `path`.

## Value

Greatly simplifies scenarios where you want to exclude a specific file(s) or folder(s), and not need to call out includes for everything else.

## Design

Both of the below proposed design changes to the `.vela.yml` would have the same underlying results of:

- Commit that changes `cool-code/foo.js` will trigger
- Commit that changes `cool-code/docs/foo.md` will not trigger

### proposed option 1

Add `ignore` and `include` underneath `path` to allow the following configuration:

```yaml
ruleset:
  path: 
    include:
      - [ "cool-code/**" ]
    exclude:
      - [ "cool-code/docs/**"]
```

This could lead to breaking behavior due to the current structure of the yaml so extra consideration is needed.

### proposed option 2

Utilize some ignore character(s) to allow updating the existing `path` to handle both scenarios. The following example utilizes the ignore character of `!`:

```yaml
ruleset:
  path: [ "!cool-code/docs/**", "cool-code/** ]
```

## Definition of Done

`ruleset` for `path` updated to allow include and exclude logic 

## Effort  (Optional)

1 day

## Impacted Personas (Optional)

All users utilizing the `ruleset` of `path`

**Comment by jbrockopp** [comment]
Hello 👋 

The Vela admins have decided to condense all existing issues into a single repo found @ [go-vela/community](https://github.com/go-vela/community).

For a direct link to your counterpart issue in that repo, you can find it linked yesterday in the history of this issue.

If you have any questions, please feel free to direct them to the community repo.

Thanks for your input and feedback!
