### ISSUE TITLE
Create JSON Schema to utilize with code editors

### ISSUE THREAD

**Issue by JordanSussman** [go-vela/types#67]
## Description

Create a [JSON schema](https://json-schema.org/) to allow code editors to parse the `.vela.yml` and help users understand if the format is valid or not.

The simple steps to test the JSON schema:

1. convert complex `.vela.yml` from yaml to json
2. utilize https://jsonschema.net/home to create JSON schema
3. follow editor specific instructions to utilize the schema for `.vela.yml`
   - VScode docs https://code.visualstudio.com/docs/languages/json#_json-schemas-and-settings

## Definition of Done

Users able to configure code editor to utilize published JSON schema for file validation

## Effort  (Optional)

2 days

## Impacted Personas (Optional)

All users modifying `.vela.yml` within any code editor

**Comment by jbrockopp** [comment]
Hello 👋 

The Vela admins have decided to condense all existing issues into a single repo found @ [go-vela/community](https://github.com/go-vela/community).

For a direct link to your counterpart issue in that repo, you can find it linked yesterday in the history of this issue.

If you have any questions, please feel free to direct them to the community repo.

Thanks for your input and feedback!
